name: Deploy ApplyFlow Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 (No Downtime)
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd /home/ec2-user/applyflow-backend

            echo "Pulling latest code..."
            git pull origin main

            echo "Building and restarting containers (no downtime)..."
            docker-compose up --build -d

            echo "Deployment complete!"
          EOF

      - name: Health Check
        run: |
          sleep 5  # small buffer to ensure container boot
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.DOMAIN }}/api/health)
          if [ "$STATUS" == "200" ]; then
            echo "200 OK"
          else
            echo "Failed with code: $STATUS"
            exit 1
          fi
